[shell]
program = '/bin/zsh'
args = ["-l"]
[window]
padding = {x = 20, y = 0}
startup_mode = "Maximized"
[font]
# normal = {family = "Iosevka Nerd Font Mono"}
normal = {family = "iMWritingMonoS Nerd Font"}
size = 13
